# Generated by Django 5.2.4 on 2025-07-04 11:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lot_no', models.CharField(help_text='Unique Lot number', max_length=100, unique=True)),
                ('party_name', models.CharField(max_length=200)),
                ('initial_meters', models.DecimalField(decimal_places=2, max_digits=10)),
                ('inward_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_no', models.CharField(max_length=100)),
                ('meters', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('AWAITING_PROCESS', 'Awaiting Process'), ('IN_PROCESS', 'In Process'), ('COMPLETED', 'Completed'), ('ON_HOLD', 'On Hold')], default='AWAITING_PROCESS', max_length=20)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('current_machine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tracking.machine')),
                ('current_operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tracking.user')),
                ('current_process', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tracking.process')),
                ('current_trolley', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tracking.trolley')),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='tracking.lot')),
            ],
            options={
                'verbose_name_plural': 'Batches',
                'unique_together': {('lot', 'batch_no')},
            },
        ),
    ]
